spring:
  profiles:
    active: dev1
---
server:
  port: 9002
spring:
  application:
    name: USER-PROVIDER1
  profiles: dev1
---
server:
  port: 9003
spring:
  application:
    name: USER-PROVIDER2
  profiles: dev2
