spring:
  profiles:
    active: 
    - dev
---
server:
  port: 8001
spring:
  application:
    name: USER-PROVIDER1
  profiles: dev
---
server:
  port: 8002
spring:
  application:
    name: USER-PROVIDER2
  profiles: test
